version: "3.9"

services:
  app:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - /home/aminesrr/Schwarzapp/data:/app/data
    networks:
      - schwarznetwork
    depends_on:
      - db

  db:
    image: mongo
    volumes:
      - mongo-data:/data/db
    networks:
      - schwarznetwork

volumes:
  mongo-data:

networks:
  schwarznetwork:
    driver: bridge 

